language: ruby
rvm:
  - 2.2.0
cache: bundler
bundler_args: --without production
notifications:
  email: false
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database monsieur_test;' -U postgres
  - bundle exec rake db:migrate
script:
  - bundle exec rspec --format progress
