redis:
  image: redis:latest
  expose:
    - "6379"

db:
  image: postgres:9.4.1
  expose:
    - "5432"

worker:
  build: .
  command: bundle exec sidekiq
  env_file: .env
  links:
    - db
    - redis

web:
  build: .
  command: bundle exec unicorn -c ./config/unicorn.rb
  env_file: .env
  environment:
    - PORT=80
    - RACK_ENV=production
  ports:
    - "5000:80"
  links:
    - db
    - redis
  volumes:
    - .:/app
