default: &default
  adapter: postgresql

development:
  <<: *default
  database: bouncer-dev

test:
  <<: *default
  database: bouncer-test
production:
  <<: *default
  database: bouncer
  pool: 5
  username: postgres
  password:
  host: db
