default: &default
  adapter: postgresql

development:
  <<: *default
  database: bouncer-dev

test:
  <<: *default
  database: bouncer-test

docker:
  <<: *default
  database: bouncer
  pool: 5
  username: postgres
  password:
  host: db

production:
  <<: *default
  database: bouncer
  pool: 5
  username: postgres
  password:
  host: db
